### ISSUE TITLE
Add asset build instructions to readme

### ISSUE THREAD

**Issue by pdt256** [pdt256/canipoop#3]
What is the recommended way to build the scss assets for this project so that github pages can serve it up.

**Comment by kyleconkright** [comment]
@jasonraimondi Should we add webpack? You can assign that to me if you want.

**Comment by pdt256** [comment]
Would be great to have a Makefile to make this easy.

`make init` and `make assets` are good options

**Comment by jasonraimondi** [comment]
@kyleconkright at first I was trying to keep this super simple, if we really wanted to expand on this in the future i think we should definitely incorporate a build. 

We also still need to add a makefile.
